### ISSUE TITLE
Potential For Conversion to a JS/CSS/HTML Library

### ISSUE THREAD

**Issue by ashesfall** [bmlt-enabled/bmlt_tabbed_map#43]
I don't know how to reach the developers of this project except by filing an issue, but basically I would like to explore how this could be converted to a library that does not require PHP as I would like to include it in another GPL project that is using react. Can you contact me to discuss this if it interests you? ashesfall@almostrealism.com

**Comment by paulnagle** [comment]
Hello, sure this could be converted to plain javascript pretty easilyt . In fact it started out as js/css only, and I added on the php bits to make it a wordpress plugin. 
Everything that you need should be in the https://github.com/bmlt-enabled/bmlt_tabbed_map/tree/master/public folder
What is the GPL product that you would like to include this in?

**Comment by ashesfall** [comment]
Well it doesn’t exist yet, but I wanted to create something of a website template for NA Area’s to use to create their web presence easily. I’d be using it initially for the Peninsula Area (CA, USA), as I am the web coordinator for that area.

-Michael M

**Comment by paulnagle** [comment]
Also we have a facebook group. https://www.facebook.com/groups/bmltapp

**Comment by paulnagle** [comment]
This is the slack link. https://bmlt.slack.com/

**Comment by ashesfall** [comment]
Can you add ashesfall@almostrealism.com <mailto:ashesfall@almostrealism.com> to slack?

-M

**Comment by paulnagle** [comment]
Invite sent!
