### ISSUE TITLE
"Click to Call" isn't generating tel: links

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt_tabbed_map#51]
The "click to call" link that is displayed for virtual or hybrid meetings is just taking the static information from the Phone Meeting Dial-in Number field in the root server and appending it as a regular hyperlink. The plugin needs to generate a tel: hyperlink with just the dial-in number for the click to call to work.

**Comment by paulnagle** [comment]
Thanks Adam, I'll push out an update to fix this
